#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Daniel Thompson-Yvetot and CrabNebula
# SPDX-License-Identifier: Apache-2.0

"""Maintain the Rust dependency section of Third_Party_Open_Source_Software_Notice.txt.

The section lists every crate reachable from the workspace through normal and
build dependencies on any target (development-only dependencies are excluded),
in the same entry form as the rest of the notice, followed by appendices with
the license texts that the notice did not already contain. It is written
between two marker lines at the end of the notice and replaced on every run,
so the script is safe to re-run after a dependency change. Run it from the
repository root:

    python3 rust/tools/third_party_notices.py

Crates offered under a choice of licenses are used under the first license of
PREFERENCE that the crate offers. License texts come from the SPDX license
list and live in rust/tools/licenses/.
"""
import collections
import glob
import json
import os
import re
import subprocess

NOTICE = "Third_Party_Open_Source_Software_Notice.txt"
BEGIN = "BEGIN RUST SDK DEPENDENCIES (generated by rust/tools/third_party_notices.py; do not edit by hand)"
END = "END RUST SDK DEPENDENCIES"
RULE = "=" * 80
SEP = "-" * 80

# Licenses in order of preference, with the display name and the appendix that
# carries the text. Appendices A to C already exist in the notice; the others are
# generated from rust/tools/licenses/<id>.txt.
PREFERENCE = [
    ("MIT", "MIT License", "B", None),
    ("ISC", "ISC License", "E", "ISC"),
    ("Apache-2.0", "Apache License 2.0", "A", None),
    ("BSD-3-Clause", "BSD 3-Clause License", "D", "BSD-3-Clause"),
    ("Zlib", "zlib License", "F", "Zlib"),
    ("Unicode-3.0", "Unicode License v3", "G", "Unicode-3.0"),
    ("MPL-2.0", "Mozilla Public License 2.0", "C", None),
    ("CDLA-Permissive-2.0", "Community Data License Agreement - Permissive 2.0", "H", "CDLA-Permissive-2.0"),
]


def choose(expression):
    ids = {t for t in re.findall(r"[A-Za-z0-9.+-]+", expression) if t not in ("OR", "AND", "WITH")}
    for entry in PREFERENCE:
        if entry[0] in ids:
            return entry
    raise SystemExit(f"no preferred license for expression {expression!r}; extend PREFERENCE")


def copyright_lines(package):
    crate_dir = os.path.dirname(package["manifest_path"])
    candidates = sorted(
        f for f in glob.glob(os.path.join(crate_dir, "*"))
        if os.path.isfile(f) and re.match(r"(?i)(licen[cs]e|copying|notice)", os.path.basename(f))
    )
    for path in candidates:
        with open(path, errors="replace") as fh:
            lines = [l.strip() for l in fh]
        found = []
        for line in lines:
            if re.match(r"(?i)copyright\s*((\(c\)|©)\s*)?[0-9(]", line) or re.match(r"(?i)copyright\s*(\(c\)|©)", line):
                found.append(re.sub(r"\s+", " ", line))
            elif found:
                break
        if found:
            return found[:4]
    authors = [re.sub(r"\s*<[^>]*>", "", a).strip() for a in package.get("authors") or []]
    authors = [a for a in authors if a]
    holders = ", ".join(authors) if authors else f"the {package['name']} developers"
    return [f"Copyright (c) {holders}"]


def reachable_packages():
    meta = json.loads(subprocess.check_output(["cargo", "metadata", "--format-version", "1"]))
    workspace = set(meta["workspace_members"])
    resolve = {n["id"]: n for n in meta["resolve"]["nodes"]}
    packages = {p["id"]: p for p in meta["packages"]}
    reachable, stack = set(), list(workspace)
    while stack:
        pid = stack.pop()
        if pid in reachable:
            continue
        reachable.add(pid)
        for dep in resolve[pid]["deps"]:
            if {k.get("kind") for k in dep["dep_kinds"]} - {"dev"}:
                stack.append(dep["pkg"])
    return sorted((packages[pid] for pid in reachable - workspace), key=lambda p: (p["name"], p["version"]))


def render(packages):
    out = [RULE, BEGIN, RULE, "",
           "RUST SDK DEPENDENCIES", "",
           "The Rust SDKs (MCP/rust-sdk, A2A/rust-sdk, A4P/rust-sdk, AgentRegistry/rust-sdk and",
           "the crates under rust/) depend on the following crates. They are fetched from",
           "crates.io at build time and are not distributed in this repository. Development-only",
           "dependencies are not listed. Where a crate is offered under a choice of licenses, the",
           "license it is used under is given in parentheses.", ""]
    used = collections.OrderedDict()
    for i, package in enumerate(packages):
        expression = package.get("license") or "(see repository)"
        spdx, name, appendix, _ = choose(expression)
        used[spdx] = True
        license_line = expression if expression == spdx else f"{expression} (used under the {name})"
        if i:
            out.append(SEP)
        out += [f"Software: {package['name']} {package['version']}", "", f"License: {license_line}", ""]
        out += copyright_lines(package)
        out += ["", f"Please see the full {name} text in Appendix {appendix}.", ""]
    for spdx, name, appendix, text_file in PREFERENCE:
        if text_file is None or spdx not in used:
            continue
        with open(os.path.join(os.path.dirname(__file__), "licenses", f"{text_file}.txt")) as fh:
            text = fh.read().rstrip("\n")
        out += [RULE, f"APPENDIX {appendix}: {name.upper()}", RULE, "", text, ""]
    out += [RULE, END, RULE]
    return "\n".join(out) + "\n"


def main():
    with open(NOTICE) as fh:
        notice = fh.read()
    section = render(reachable_packages())
    pattern = re.compile(re.escape(RULE + "\n" + BEGIN) + ".*?" + re.escape(END + "\n" + RULE + "\n"), re.S)
    if pattern.search(notice):
        notice = pattern.sub(lambda _: section, notice)
    else:
        notice = notice.rstrip("\n") + "\n\n" + section
    with open(NOTICE, "w") as fh:
        fh.write(notice)


if __name__ == "__main__":
    main()
